#!/bin/sh

# Copyright 2017-2019 Raytheon BBN Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Survey the ciphersuites used by the top 200K sites from the
# current Alexa top 1m list, against the ciphersuites offered
# used by several popular browsers.
#
# This script does not update the ciphersuites: that still needs
# to be done by hand.

# If SSL isn't set, nothing will work
#
if [ -z ${SSL+x} ]; then
    echo "ERROR: SSL is not set"
    exit 1
fi

# Don't run this script right before midnight; it could get weird.
#
DATE=$(date +%Y%m%d)
OUTDIR="OUT-$DATE"

ALEXAFILE=top-1m.csv.zip
HOSTFILE="alexa-1m-${DATE}.txt"

rm -f "${ALEXAFILE}" "${HOSTFILE}"
if [ -f "${ALEXAFILE}" ]; then
    echo "ERROR: could not remove $ALEXAFILE"
    exit 1
fi

if [ -f "${HOSTFILE}" ]; then
    echo "ERROR: could not remove $HOSTFILE"
    exit 1
fi

wget "http://s3.amazonaws.com/alexa-static/${ALEXAFILE}"
if [ ! -f "${ALEXAFILE}" ]; then
    echo "ERROR: $ALEXAFILE could not be fetched"
    exit 1
fi

unzip -qc "${ALEXAFILE}" | sed -e 's/^.*,//' > "${HOSTFILE}"
rm -f "${ALEXAFILE}"

mkdir -p "${OUTDIR}"
if [ ! -d "${OUTDIR}" ]; then
    echo "ERROR: cannot create output directory ${OUTDIR}"
    exit 1
fi

for browser in chrome firefox edge safari ; do
    for start in 0 2 4 6 7 10 12 14 16 18; do
	base=$((start * 10000))
	./test-slice $base 20000 t-"${browser}-alike" \
		"${HOSTFILE}" "${OUTDIR}" &
    done
done

wait

for browser in chrome firefox edge safari ; do
    summ="${OUTDIR}"/"${browser}"-200k.txt
    touch "${summ}"

    for start in 0 2 4 6 7 10 12 14 16 18; do
	base=$((start * 10000))
	cat "${OUTDIR}/out-t-${browser}-alike-$base"-*.txt >> "${summ}"
    done
done

echo "SURVEY DONE"
